"""
OASIS Classroom Discussion Simulation
Adapted from run_reddit_simulation.py for AP Social Studies.

Runs a simulated classroom discussion on the Reddit platform engine
(posts = arguments, comments = responses, likes = agreement, dislikes = disagreement).

Features:
- Loads student profiles generated by StudentProfileGenerator
- Executes teacher interventions at configured rounds
- Supports post-simulation interview/assessment of each student agent
- Writes action log to classroom/actions.jsonl

Usage:
    python run_classroom_simulation.py --config /path/to/ap_config.json --profiles /path/to/profiles.json
    python run_classroom_simulation.py --config /path/to/ap_config.json --profiles /path/to/profiles.json --no-wait
    python run_classroom_simulation.py --config /path/to/ap_config.json --generate-profiles  # generate + run
"""

import argparse
import asyncio
import json
import logging
import os
import random
import signal
import sqlite3
import sys
from datetime import datetime
from typing import Any, Dict, List, Optional

# ── path setup ───────────────────────────────────────────────────────────────
_scripts_dir = os.path.dirname(os.path.abspath(__file__))
_backend_dir = os.path.abspath(os.path.join(_scripts_dir, ".."))
_project_root = os.path.abspath(os.path.join(_backend_dir, ".."))
sys.path.insert(0, _scripts_dir)
sys.path.insert(0, _backend_dir)

from dotenv import load_dotenv

_env_file = os.path.join(_project_root, ".env")
if os.path.exists(_env_file):
    load_dotenv(_env_file)

# ── globals ──────────────────────────────────────────────────────────────────
_shutdown_event: Optional[asyncio.Event] = None
_cleanup_done = False

# ── OASIS imports ────────────────────────────────────────────────────────────
try:
    from camel.models import ModelFactory
    from camel.types import ModelPlatformType
    import oasis
    from oasis import (
        ActionType,
        LLMAction,
        ManualAction,
        generate_reddit_agent_graph,
    )
except ImportError as e:
    print(f"Error: missing dependency {e}")
    print("Install with: pip install oasis-ai camel-ai")
    sys.exit(1)


# ── Logging ──────────────────────────────────────────────────────────────────
def setup_logging(log_dir: str):
    os.makedirs(log_dir, exist_ok=True)
    handler = logging.FileHandler(
        os.path.join(log_dir, "classroom_simulation.log"), encoding="utf-8", mode="w"
    )
    handler.setFormatter(logging.Formatter("%(levelname)s - %(asctime)s - %(name)s - %(message)s"))
    root = logging.getLogger()
    root.setLevel(logging.INFO)
    root.addHandler(handler)


# ── Action logger (JSONL) ────────────────────────────────────────────────────
class ActionLogger:
    """Append agent actions to a JSONL file for downstream analysis."""

    def __init__(self, output_dir: str):
        os.makedirs(output_dir, exist_ok=True)
        self.path = os.path.join(output_dir, "actions.jsonl")
        self._f = open(self.path, "a", encoding="utf-8")

    def log_event(self, event_type: str, **kwargs):
        record = {"event_type": event_type, "timestamp": datetime.now().isoformat(), **kwargs}
        self._f.write(json.dumps(record, ensure_ascii=False) + "\n")
        self._f.flush()

    def log_action(self, round_num: int, agent_id: int, agent_name: str, action_type: str, **kwargs):
        record = {
            "round": round_num,
            "timestamp": datetime.now().isoformat(),
            "agent_id": agent_id,
            "agent_name": agent_name,
            "action_type": action_type,
            **kwargs,
        }
        self._f.write(json.dumps(record, ensure_ascii=False) + "\n")
        self._f.flush()

    def close(self):
        self._f.close()


# ── IPC (reuse from Reddit runner pattern) ───────────────────────────────────
IPC_COMMANDS_DIR = "ipc_commands"
IPC_RESPONSES_DIR = "ipc_responses"
ENV_STATUS_FILE = "env_status.json"


class IPCHandler:
    """Minimal IPC handler for post-simulation interview commands."""

    def __init__(self, sim_dir: str, env, agent_graph):
        self.sim_dir = sim_dir
        self.env = env
        self.agent_graph = agent_graph
        self.commands_dir = os.path.join(sim_dir, IPC_COMMANDS_DIR)
        self.responses_dir = os.path.join(sim_dir, IPC_RESPONSES_DIR)
        self.status_file = os.path.join(sim_dir, ENV_STATUS_FILE)
        os.makedirs(self.commands_dir, exist_ok=True)
        os.makedirs(self.responses_dir, exist_ok=True)

    def update_status(self, status: str):
        with open(self.status_file, "w", encoding="utf-8") as f:
            json.dump({"status": status, "timestamp": datetime.now().isoformat()}, f)

    def poll_command(self) -> Optional[Dict[str, Any]]:
        if not os.path.exists(self.commands_dir):
            return None
        for fn in sorted(os.listdir(self.commands_dir)):
            if fn.endswith(".json"):
                fp = os.path.join(self.commands_dir, fn)
                try:
                    with open(fp, "r", encoding="utf-8") as f:
                        return json.load(f)
                except (json.JSONDecodeError, OSError):
                    continue
        return None

    def send_response(self, command_id: str, status: str, result=None, error=None):
        resp = {
            "command_id": command_id,
            "status": status,
            "result": result,
            "error": error,
            "timestamp": datetime.now().isoformat(),
        }
        with open(os.path.join(self.responses_dir, f"{command_id}.json"), "w", encoding="utf-8") as f:
            json.dump(resp, f, ensure_ascii=False, indent=2)
        try:
            os.remove(os.path.join(self.commands_dir, f"{command_id}.json"))
        except OSError:
            pass

    async def handle_interview(self, command_id: str, agent_id: int, prompt: str):
        try:
            agent = self.agent_graph.get_agent(agent_id)
            action = ManualAction(action_type=ActionType.INTERVIEW, action_args={"prompt": prompt})
            await self.env.step({agent: action})
            result = self._get_interview_result(agent_id)
            self.send_response(command_id, "completed", result=result)
        except Exception as e:
            self.send_response(command_id, "failed", error=str(e))

    async def handle_batch_interview(self, command_id: str, interviews: List[Dict]):
        try:
            actions = {}
            for item in interviews:
                aid = item.get("agent_id")
                prompt = item.get("prompt", "")
                try:
                    agent = self.agent_graph.get_agent(aid)
                    actions[agent] = ManualAction(
                        action_type=ActionType.INTERVIEW, action_args={"prompt": prompt}
                    )
                except Exception:
                    pass
            if not actions:
                self.send_response(command_id, "failed", error="No valid agents")
                return
            await self.env.step(actions)
            results = {
                item["agent_id"]: self._get_interview_result(item["agent_id"]) for item in interviews
            }
            self.send_response(command_id, "completed", result={"results": results})
        except Exception as e:
            self.send_response(command_id, "failed", error=str(e))

    def _get_interview_result(self, agent_id: int) -> Dict:
        db_path = os.path.join(self.sim_dir, "classroom_simulation.db")
        result = {"agent_id": agent_id, "response": None, "timestamp": None}
        if not os.path.exists(db_path):
            return result
        try:
            conn = sqlite3.connect(db_path)
            cur = conn.cursor()
            cur.execute(
                "SELECT user_id, info, created_at FROM trace "
                "WHERE action = ? AND user_id = ? ORDER BY created_at DESC LIMIT 1",
                (ActionType.INTERVIEW.value, agent_id),
            )
            row = cur.fetchone()
            if row:
                info = json.loads(row[1]) if row[1] else {}
                result["response"] = info.get("response", info)
                result["timestamp"] = row[2]
            conn.close()
        except Exception as e:
            print(f"  Failed to read interview result: {e}")
        return result

    async def process_commands(self) -> bool:
        cmd = self.poll_command()
        if not cmd:
            return True
        cid = cmd.get("command_id")
        ctype = cmd.get("command_type")
        args = cmd.get("args", {})
        print(f"\n  IPC command: {ctype} (id={cid})")
        if ctype == "interview":
            await self.handle_interview(cid, args.get("agent_id", 0), args.get("prompt", ""))
        elif ctype == "batch_interview":
            await self.handle_batch_interview(cid, args.get("interviews", []))
        elif ctype == "close_env":
            self.send_response(cid, "completed", result={"message": "Shutting down"})
            return False
        else:
            self.send_response(cid, "failed", error=f"Unknown command: {ctype}")
        return True


# ── Main runner ──────────────────────────────────────────────────────────────

class ClassroomSimulationRunner:
    """
    Runs an AP classroom discussion using OASIS Reddit as the underlying engine.

    Mapping:
        Reddit POST     → Student making an argument / raising a point
        Reddit COMMENT  → Responding to a peer
        Reddit LIKE     → Agreeing with a point
        Reddit DISLIKE  → Disagreeing with a point
        Reddit SEARCH   → Looking up information
        DO_NOTHING      → Staying silent
    """

    AVAILABLE_ACTIONS = [
        ActionType.LIKE_POST,
        ActionType.DISLIKE_POST,
        ActionType.CREATE_POST,
        ActionType.CREATE_COMMENT,
        ActionType.LIKE_COMMENT,
        ActionType.DISLIKE_COMMENT,
        ActionType.SEARCH_POSTS,
        ActionType.DO_NOTHING,
    ]

    def __init__(self, config_path: str, profiles_path: str, wait_for_commands: bool = True):
        self.config_path = config_path
        self.profiles_path = profiles_path
        self.wait_for_commands = wait_for_commands

        with open(config_path, "r", encoding="utf-8") as f:
            self.config = json.load(f)

        self.sim_dir = os.path.dirname(os.path.abspath(profiles_path))
        self.env = None
        self.agent_graph = None
        self.ipc_handler = None

    def _create_model(self):
        llm_api_key = os.environ.get("LLM_API_KEY", "")
        llm_base_url = os.environ.get("LLM_BASE_URL", "")
        llm_model = os.environ.get("LLM_MODEL_NAME", "gpt-4o-mini")

        if llm_api_key:
            os.environ["OPENAI_API_KEY"] = llm_api_key
        if llm_base_url:
            os.environ["OPENAI_API_BASE_URL"] = llm_base_url

        if not os.environ.get("OPENAI_API_KEY"):
            raise ValueError("Missing LLM_API_KEY in .env")

        print(f"  LLM: model={llm_model}, base_url={llm_base_url[:40] if llm_base_url else 'default'}...")
        return ModelFactory.create(model_platform=ModelPlatformType.OPENAI, model_type=llm_model)

    def _get_active_students(self, round_num: int, total_rounds: int) -> List[int]:
        """
        Decide which students are active this round based on engagement level.
        Early rounds (warmup) → fewer students.
        Late rounds (cooldown) → fewer students.
        Middle rounds → peak participation.
        """
        discussion = self.config.get("discussion_config", {})
        warmup = discussion.get("warmup_rounds", 2)
        cooldown = discussion.get("cooldown_rounds", 1)

        # Participation multiplier based on round phase
        if round_num < warmup:
            phase_mult = 0.4 + (round_num / warmup) * 0.3  # ramp up
        elif round_num >= total_rounds - cooldown:
            phase_mult = 0.5  # wind down
        else:
            phase_mult = 1.0  # full engagement

        # Load profile data for engagement levels
        with open(self.profiles_path, "r", encoding="utf-8") as f:
            profiles = json.load(f)

        active_ids = []
        for p in profiles:
            uid = p["user_id"]
            # Engagement is baked into the persona; approximate from karma/archetype
            # Higher karma → more engaged (our generator sets karma proportional to engagement)
            base_chance = min(p.get("karma", 100) / 500.0, 1.0) * phase_mult

            if random.random() < base_chance:
                active_ids.append(uid)

        # Ensure at least 3 students are active per round
        if len(active_ids) < 3 and profiles:
            extras = random.sample(
                [p["user_id"] for p in profiles],
                min(3 - len(active_ids), len(profiles)),
            )
            active_ids = list(set(active_ids + extras))

        return active_ids

    def _get_teacher_intervention(self, round_num: int) -> Optional[str]:
        """Check if there's a teacher intervention scheduled for this round."""
        interventions = (
            self.config.get("discussion_config", {}).get("teacher_interventions", [])
        )
        for inv in interventions:
            if inv.get("trigger_round") == round_num:
                return inv.get("content", "")
        return None

    async def run(self):
        """Main simulation loop."""
        discussion = self.config.get("discussion_config", {})
        total_rounds = discussion.get("total_rounds", 12)
        minutes_per_round = discussion.get("minutes_per_round", 5)
        meta = self.config.get("simulation_meta", {})
        classroom = self.config.get("classroom_context", {})

        print("=" * 65)
        print("  🏫  AP CLASSROOM DISCUSSION SIMULATION")
        print("=" * 65)
        print(f"  Subject:    {meta.get('subject', 'AP Social Studies')}")
        print(f"  Unit:       {meta.get('unit', '')}")
        print(f"  Teacher:    {classroom.get('teacher_name', 'Teacher')}")
        print(f"  Format:     {classroom.get('discussion_format', 'discussion')}")
        print(f"  Rounds:     {total_rounds} × {minutes_per_round} min")
        print(f"  Profiles:   {self.profiles_path}")
        print(f"  Wait mode:  {'ON' if self.wait_for_commands else 'OFF'}")
        print("=" * 65)

        # Init
        print("\n  Initializing LLM model...")
        model = self._create_model()

        print("  Loading student profiles...")
        if not os.path.exists(self.profiles_path):
            print(f"  ERROR: Profile file not found: {self.profiles_path}")
            return

        self.agent_graph = await generate_reddit_agent_graph(
            profile_path=self.profiles_path,
            model=model,
            available_actions=self.AVAILABLE_ACTIONS,
        )

        db_path = os.path.join(self.sim_dir, "classroom_simulation.db")
        if os.path.exists(db_path):
            os.remove(db_path)

        print("  Creating OASIS environment...")
        self.env = oasis.make(
            agent_graph=self.agent_graph,
            platform=oasis.DefaultPlatformType.REDDIT,
            database_path=db_path,
            semaphore=20,
        )
        await self.env.reset()

        # IPC
        self.ipc_handler = IPCHandler(self.sim_dir, self.env, self.agent_graph)
        self.ipc_handler.update_status("running")

        # Action logger
        log_dir = os.path.join(self.sim_dir, "classroom")
        action_logger = ActionLogger(log_dir)
        action_logger.log_event("simulation_start", total_rounds=total_rounds)

        # Seed the discussion with the teacher's opening prompt
        seed_prompt = classroom.get("seed_prompt", "")
        if seed_prompt:
            print(f"\n  📢 Teacher opens discussion:")
            print(f"     \"{seed_prompt[:120]}...\"" if len(seed_prompt) > 120 else f"     \"{seed_prompt}\"")
            # Post as agent 0 (first student) acting as proxy for the teacher prompt
            # In a real extension we'd add a teacher agent; for now use ManualAction
            try:
                teacher_agent = self.env.agent_graph.get_agent(0)
                teacher_post = ManualAction(
                    action_type=ActionType.CREATE_POST,
                    action_args={
                        "content": f"[DISCUSSION PROMPT from {classroom.get('teacher_name', 'Teacher')}]: {seed_prompt}"
                    },
                )
                await self.env.step({teacher_agent: teacher_post})
                action_logger.log_action(
                    round_num=0, agent_id=0, agent_name="TEACHER",
                    action_type="SEED_PROMPT", content=seed_prompt,
                )
                print("     ✓ Discussion prompt posted\n")
            except Exception as e:
                print(f"     ⚠ Failed to post seed prompt: {e}\n")

        # ── Main discussion loop ─────────────────────────────────────────────
        print("  Starting discussion rounds...\n")
        start_time = datetime.now()

        for round_num in range(total_rounds):
            simulated_minute = round_num * minutes_per_round
            round_label = f"Round {round_num + 1}/{total_rounds} ({simulated_minute}-{simulated_minute + minutes_per_round} min)"

            # Teacher intervention?
            intervention = self._get_teacher_intervention(round_num)
            if intervention:
                print(f"  📢 TEACHER [{round_label}]: \"{intervention[:100]}...\"")
                try:
                    t_agent = self.env.agent_graph.get_agent(0)
                    t_action = ManualAction(
                        action_type=ActionType.CREATE_POST,
                        action_args={
                            "content": f"[TEACHER — {classroom.get('teacher_name', 'Teacher')}]: {intervention}"
                        },
                    )
                    await self.env.step({t_agent: t_action})
                    action_logger.log_action(
                        round_num=round_num, agent_id=-1, agent_name="TEACHER",
                        action_type="INTERVENTION", content=intervention,
                    )
                except Exception as e:
                    print(f"     ⚠ Teacher intervention failed: {e}")

            # Get active students
            active_ids = self._get_active_students(round_num, total_rounds)
            if not active_ids:
                action_logger.log_event("round_end", round=round_num, active_count=0)
                continue

            # Build LLM actions
            actions = {}
            for aid in active_ids:
                try:
                    agent = self.env.agent_graph.get_agent(aid)
                    actions[agent] = LLMAction()
                except Exception:
                    pass

            if actions:
                await self.env.step(actions)

            # Log
            action_logger.log_event(
                "round_end", round=round_num,
                active_count=len(active_ids),
                simulated_minutes=simulated_minute + minutes_per_round,
            )

            elapsed = (datetime.now() - start_time).total_seconds()
            print(
                f"  [{round_label}] {len(active_ids)} students active | "
                f"elapsed: {elapsed:.1f}s"
            )

        # ── End of discussion ────────────────────────────────────────────────
        total_elapsed = (datetime.now() - start_time).total_seconds()
        action_logger.log_event("simulation_end", total_rounds=total_rounds)
        action_logger.close()

        print(f"\n  ✅ Discussion complete! ({total_elapsed:.1f}s)")
        print(f"     Database:    {db_path}")
        print(f"     Action log:  {action_logger.path}")

        # ── Run assessment prompts automatically ─────────────────────────────
        assessment_prompts = self.config.get("assessment_prompts", [])
        if assessment_prompts:
            print(f"\n  📝 Running {len(assessment_prompts)} assessment prompts...")
            for ap in assessment_prompts:
                prompt_text = ap.get("prompt", "")
                target = ap.get("target", "all")
                ap_id = ap.get("id", "unknown")

                # Determine target agents
                with open(self.profiles_path, "r", encoding="utf-8") as f:
                    all_profiles = json.load(f)

                if target == "all":
                    target_ids = [p["user_id"] for p in all_profiles]
                else:
                    # target is a comma-separated list of archetype_ids
                    # We need to match against the profile persona or bio
                    target_archetypes = set(t.strip() for t in target.split(","))
                    target_ids = []
                    # We store archetype info in the persona text; for now assess all
                    target_ids = [p["user_id"] for p in all_profiles]

                print(f"     [{ap_id}] Assessing {len(target_ids)} students...")

                interview_actions = {}
                for tid in target_ids:
                    try:
                        agent = self.env.agent_graph.get_agent(tid)
                        interview_actions[agent] = ManualAction(
                            action_type=ActionType.INTERVIEW,
                            action_args={"prompt": prompt_text},
                        )
                    except Exception:
                        pass

                if interview_actions:
                    await self.env.step(interview_actions)
                    print(f"     ✓ {ap_id} complete ({len(interview_actions)} responses)")

        # ── Wait for commands (interview mode) ───────────────────────────────
        if self.wait_for_commands:
            print("\n" + "=" * 65)
            print("  Entering interview mode — environment stays alive")
            print("  Send IPC commands: interview, batch_interview, close_env")
            print("=" * 65)

            self.ipc_handler.update_status("alive")

            try:
                while not _shutdown_event.is_set():
                    should_continue = await self.ipc_handler.process_commands()
                    if not should_continue:
                        break
                    try:
                        await asyncio.wait_for(_shutdown_event.wait(), timeout=0.5)
                        break
                    except asyncio.TimeoutError:
                        pass
            except (KeyboardInterrupt, asyncio.CancelledError):
                pass

        # Cleanup
        self.ipc_handler.update_status("stopped")
        await self.env.close()
        print("\n  Environment closed. Goodbye! 👋")


# ── CLI ──────────────────────────────────────────────────────────────────────

async def main():
    parser = argparse.ArgumentParser(description="AP Classroom Discussion Simulation")
    parser.add_argument("--config", type=str, required=True, help="AP config JSON path")
    parser.add_argument("--profiles", type=str, default=None, help="Profiles JSON path (if already generated)")
    parser.add_argument("--generate-profiles", action="store_true", help="Generate profiles from config first")
    parser.add_argument("--no-llm", action="store_true", help="Skip LLM for profile generation")
    parser.add_argument("--no-wait", action="store_true", help="Exit immediately after simulation")
    parser.add_argument("--output-dir", type=str, default=None, help="Output directory (default: same as config)")
    args = parser.parse_args()

    global _shutdown_event
    _shutdown_event = asyncio.Event()

    if not os.path.exists(args.config):
        print(f"Error: Config not found: {args.config}")
        sys.exit(1)

    output_dir = args.output_dir or os.path.dirname(os.path.abspath(args.config))
    os.makedirs(output_dir, exist_ok=True)

    profiles_path = args.profiles or os.path.join(output_dir, "reddit_profiles.json")

    # Generate profiles if requested or if they don't exist
    if args.generate_profiles or not os.path.exists(profiles_path):
        print("\n  Generating student profiles...\n")
        # Import here to avoid circular deps
        sys.path.insert(0, os.path.join(_scripts_dir, ".."))
        from app.services.student_profile_generator import StudentProfileGenerator

        gen = StudentProfileGenerator()

        def progress(cur, total, msg):
            print(f"    [{cur}/{total}] {msg}")

        profiles = gen.generate_profiles(
            config_path=args.config,
            use_llm=not args.no_llm,
            progress_callback=progress,
        )
        gen.save_profiles(profiles, profiles_path)
        print(f"\n  ✓ {len(profiles)} profiles saved to {profiles_path}\n")

    setup_logging(os.path.join(output_dir, "log"))

    runner = ClassroomSimulationRunner(
        config_path=args.config,
        profiles_path=profiles_path,
        wait_for_commands=not args.no_wait,
    )
    await runner.run()


def setup_signal_handlers():
    def handler(signum, frame):
        global _cleanup_done
        print(f"\n  Signal {signum} received, shutting down...")
        if not _cleanup_done:
            _cleanup_done = True
            if _shutdown_event:
                _shutdown_event.set()
        else:
            sys.exit(1)

    signal.signal(signal.SIGTERM, handler)
    signal.signal(signal.SIGINT, handler)


if __name__ == "__main__":
    setup_signal_handlers()
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n  Interrupted")
    except SystemExit:
        pass
